version: '3.3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2:rw
      - ./influxdb_config:/etc/influxdb2:rw
    restart: unless-stopped
  mqtt_listener:
    build:
      context: .
      dockerfile: mqtt_listener.Dockerfile
    env_file:
      - mqtt_listener/.env
    environment:
      - INFLUXDB_ADDRESS=http://influxdb:8086
      - LOG_LEVEL=INFO
    depends_on:
      - influxdb
    restart: unless-stopped